server:
  port: 8855

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/blogdb
    username: gaurav
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
